### ISSUE TITLE
视频帧数和pose帧数对不上

### ISSUE THREAD

**Issue by wyy-thu** [JeffWang987/EgoVid#3]
pose目录下fused_pose.npy文件都是120帧的，但是视频帧数大于120帧，如0a47c74a-dad9-42d5-b937-0f375490f034_0_162包含163帧，且在egovid-text.csv中找不到0a47c74a-dad9-42d5-b937-0f375490f034_0_162。

**Comment by CIntellifusion** [comment]
Hello， How do you solve this? Could please provide any suggestions?
